# Generated by Django 5.2.5 on 2025-11-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('reseller', 'Reseller'), ('superadmin', 'Superadmin')], default='customer', max_length=20),
        ),
    ]
