# Generated by Django 5.2.5 on 2025-09-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unit_of_measurement', models.CharField(help_text='e.g. kg, liter, piece', max_length=20)),
                ('default_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('restock_level', models.DecimalField(decimal_places=3, help_text='Minimum quantity before restocking', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
                'ordering': ['name'],
            },
        ),
    ]
