# Generated by Django 5.2.5 on 2025-09-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_supplier_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.CharField(blank=True, help_text='e.g. Produce, Meat, Dry Goods', max_length=50),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
