# Generated by Django 5.2.5 on 2025-09-15 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_supplier_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Supplier-specific price for this ingredient', max_digits=12)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_suppliers', to='inventory.ingredient')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_suppliers', to='inventory.supplier')),
            ],
            options={
                'verbose_name': 'Ingredient Supplier',
                'verbose_name_plural': 'Ingredient Suppliers',
                'unique_together': {('supplier', 'ingredient')},
            },
        ),
    ]
