# Generated by Django 5.2.5 on 2025-09-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_ingredient_category_ingredient_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, help_text='e.g. Produce, Meat, Dry Goods', max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock', models.DecimalField(decimal_places=3, help_text='Current stock quantity', max_digits=12)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Out of Stock', 'Out of Stock')], default='Active', max_length=20)),
                ('ingredients', models.ManyToManyField(blank=True, related_name='products', to='inventory.ingredient')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
    ]
