# Generated by Django 5.2.5 on 2025-09-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(help_text='Current stock quantity'),
        ),
    ]
