# Generated by Django 5.2.5 on 2025-09-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Out of Stock', 'Out of Stock'), ('Low Stock', 'Low Stock')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Current stock quantity', max_digits=12, null=True),
        ),
    ]
