# Generated by Django 5.2.5 on 2025-09-17 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_product_status_alter_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('uom', models.CharField(blank=True, help_text='e.g. kg, L, piece', max_length=20)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_products', to='inventory.ingredient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ingredients', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Product Ingredient',
                'verbose_name_plural': 'Product Ingredients',
                'unique_together': {('product', 'ingredient')},
            },
        ),
        # Replace incompatible AlterField with Remove + Add using through
        migrations.RemoveField(
            model_name='product',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='products', through='inventory.ProductIngredient', to='inventory.ingredient'),
        ),
    ]
