# Generated by Django 5.2.5 on 2025-09-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_productingredient_alter_product_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='current_stock',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Current available quantity', max_digits=12, null=True),
        ),
    ]
