# Generated by Django 5.2.5 on 2025-09-18 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_ingredientsupplier'),
        ('inventory', '0009_ingredient_current_stock'),
    ]

    operations = [
    ]
