# Generated by Django 5.2.5 on 2025-09-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_ingredient_current_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, help_text='Current stock quantity', null=True),
        ),
    ]
