# Generated by Django 5.2.5 on 2025-09-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_merge_20250918_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientsupplier',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, help_text='Current stock quantity', null=True),
        ),
    ]
