# Generated by Django 5.2.5 on 2025-09-18 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_product_stock'),
        ('inventory', '0011_ingredientsupplier_is_active_alter_product_stock'),
    ]

    operations = [
    ]
