# Generated by Django 5.2.5 on 2025-10-13 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_merge_20250919_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Product image', null=True, upload_to='products/'),
        ),
    ]
