# Generated by Django 5.2.5 on 2025-10-12 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_merge_20250919_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResupplyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantity ordered', max_digits=12)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=20)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resupply_orders', to='inventory.ingredient')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resupply_orders', to='inventory.supplier')),
            ],
            options={
                'verbose_name': 'Resupply Order',
                'verbose_name_plural': 'Resupply Orders',
                'ordering': ['-order_date'],
            },
        ),
    ]
