# Generated by Django 5.2.5 on 2025-10-13 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
