# Generated by Django 5.2.5 on 2025-10-13 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_resupplyorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resupplyorder',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='resupplyorder',
            name='quantity',
        ),
        migrations.CreateModel(
            name='ResupplyOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantity ordered', max_digits=12)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ingredient')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.resupplyorder')),
            ],
        ),
    ]
