# Generated by Django 5.2.5 on 2025-10-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_remove_resupplyorder_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resupplyorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Pending', max_length=20),
        ),
    ]
