# Generated by Django 5.2.5 on 2025-10-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_resupplyorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resupplyorder',
            name='was_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
