# Generated by Django 5.2.5 on 2025-10-14 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_resupplyorder_was_delivered'),
        ('inventory', '0017_cart_cartitem'),
    ]

    operations = [
    ]
