# Generated by Django 5.2.5 on 2025-10-17 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_add_temporary_order_field'),
        ('inventory', '0025_add_paymongo_fields_to_order'),
    ]

    operations = [
    ]
