# Generated by Django 5.2.5 on 2025-10-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_merge_20251017_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('GCash', 'GCash'), ('Bank Transfer', 'Bank Transfer'), ('Credit Card', 'Credit Card')], default='COD', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('GCash', 'GCash'), ('Bank Transfer', 'Bank Transfer'), ('Credit Card', 'Credit Card')], max_length=20),
        ),
    ]
