# Generated by Django 5.2.5 on 2025-10-17 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_alter_order_payment_method_alter_sale_payment_method_and_more'),
    ]

    operations = [
    ]
