# Generated by Django 5.2.5 on 2025-11-11 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_checkoutsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='resupplyorderitem',
            name='quantity_ordered',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Quantity ordered (new)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='restock_level',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Minimum quantity before restocking', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='resupplyorderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, help_text='(legacy) Quantity ordered — kept for migration', max_digits=12),
        ),
        migrations.CreateModel(
            name='IngredientBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.DecimalField(decimal_places=3, help_text='Amount delivered in this batch', max_digits=12)),
                ('current_quantity', models.DecimalField(decimal_places=3, help_text='Amount remaining in this batch', max_digits=12)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('supplier_batch_code', models.CharField(blank=True, help_text='Optional supplier lot/batch code', max_length=200, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.ingredient')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='inventory.resupplyorderitem')),
            ],
            options={
                'verbose_name': 'Ingredient Batch',
                'verbose_name_plural': 'Ingredient Batches',
                'ordering': ['expiry_date', 'received_date'],
            },
        ),
    ]
