# Generated by Django 5.2.5 on 2025-11-11 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_resupplyorderitem_quantity_ordered_and_more'),
    ]

    operations = [
    ]
