# Generated by Django 5.2.5 on 2025-11-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_migrate_ingredient_to_batches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='current_stock',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='resupplyorderitem',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='resupplyorderitem',
            name='quantity_ordered',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='ingredientbatch',
            index=models.Index(fields=['ingredient', 'expiry_date'], name='inventory_i_ingredi_f1ae9d_idx'),
        ),
    ]
