# Generated by Django 5.2.5 on 2025-11-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_production_workflow'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ingredientconsumption',
            new_name='inventory_i_product_badff2_idx',
            old_name='inventory_ic_batch_ing_idx',
        ),
        migrations.RenameIndex(
            model_name='productionbatch',
            new_name='inventory_p_status_ff4926_idx',
            old_name='inventory_pr_status_idx',
        ),
        migrations.RenameIndex(
            model_name='productionbatch',
            new_name='inventory_p_window__7b2bbc_idx',
            old_name='inventory_pr_window_idx',
        ),
        migrations.AlterField(
            model_name='productionwindowconfig',
            name='default_end_time',
            field=models.TimeField(default='21:59'),
        ),
        migrations.AlterField(
            model_name='productionwindowconfig',
            name='default_start_time',
            field=models.TimeField(default='22:00'),
        ),
    ]
