# Generated by Django 5.2.5 on 2025-11-13 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_productionbatch_requirements_snapshot'),
        ('inventory', '0037_rename_inventory_ic_batch_ing_idx_inventory_i_product_badff2_idx_and_more'),
    ]

    operations = [
    ]
