# Generated by Django 5.2.5 on 2025-11-13 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_merge_20251113_2206'),
        ('inventory', '0038_productionbatch_orders_snapshot'),
    ]

    operations = [
    ]
