# Generated by Django 5.2.5 on 2025-11-14 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_merge_20251113_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientconsumption',
            name='ingredient_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_consumptions', to='inventory.ingredientbatch'),
        ),
    ]
